name: SafeFlyV2
author: Sean_M
version: "2.0.1"
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
description: Fly in survival without damaging players!
main: Sean_M\SafeFly\Main

commands:
    fly:
        description: "Activates or deactivates SafeFly."
        usage: "/fly"
        permission: safefly.fly
permissions:
  safefly.fly.off:
    description: "Turns off your fly mode when you leave."
    default: true
    
 
